const tour = [
  {title: 'STOP #1 Flag Gallery: Theme Introduction',
   slides: [
    'New York City was the stage for many of George Washington’s career trials and triumphs. Shortly after the Continental Congress agreed to independence in 1776, the General suffered his worst military defeat within the current city limits. Throughout the Revolution GW sought to regain New York from British Occupation, but his re-entry into the city would not occur until British evacuation on November 25th 1783. On December 4th, Washington bid farewell to his officers and public service in the Long Room of Fraunces Tavern. Yet, New York City beckoned him back into public life as Federal Hall (at the intersection of Broad and Wall St.) served as his inauguration site and the city as the nation’s new temporary capital in 1789. Throughout this tour we will discuss Washington’s various visits to the city and how his experiences within New York City and around, ultimately shaped and defined his public career.'
  ]},
  {title: 'STOP #2 Ratzer Map (Confidential): A Young Colonel in New York (1756)',
   slides: [
    '*Please note: The Ratzer Map, 1767, would have been the NYC Washington was familiar with during this period*',
    '1. In 1756, twenty-four-year-old Colonel George Washington first arrived to the blusting port city of New York as a crossover on a journey to and from Boston. A surveyor and seasoned soldier from Virginia, Washington was to meet with British commander-in-chief Governor William Shirley of Massachusetts, to discuss the terms of his commission within the Royal Army. At this point in time, the British Empire was engulfed in an imperial crisis against the French, known as the Seven Years’ War or by the name given to the North American theatre: The French and Indian War (1754 - 1763).',
    '2. (HANDOUT GW in Virginia Regiment Uniform and Journal title page) Washington was an established public figure and author upon his arrival to New York City. The widely read Journal of Major George Washington (1754) was Washington’s personal account of his mission as a “royal emissary” sent by Virginia Governor Robert Dinwiddie to the contested Ohio Territory. A failed diplomatic mission, Governor Dinwiddie quickly published Washington’s report. Read by fellow countrymen, King, and Parliament- the result of the Journal lead to further escalation of the Seven Years’ War.',
    '2.1 This includes General Sir Edward Braddock’s ill-fated attack on Fort Duquesne (1755). Washington, due to his notoriety, served as Braddock’s aide-de-camp. The British General was mortally wounded and later passed. Washington recalls in a letter to his Mother (Mary Ball Washington): “I luckily escaped without a wound, though I had four bullets through my coat, and two horses shot under me.”',
    '3. Dressed in his Virginia Regimental Uniform of buff-and-blue and accompanied by officers and attendants, Washington created sensation on his trip through New York. The young Colonel sought the fanfare, as he wanted to be viewed as an officer of equal standing and authority to that of a British regular officer (the purpose for meeting with Gov. Shirley in Boston).',
    '4. New York was different from the genteel Virginia society and Western territories GW was accustomed to. The city was a center of imperial culture, as profits came in from provisions provided to stationed troops, as well as illicit trade with French Caribbean Islands. New York merchants had grown extremely wealthy- in 1756, Ben Franklin observed: “That New York is growing immensely rich, by Money bought into Quarters for the Pay and Subsistence of the Troops”.',
    '4.1 In particular, the firm of De Lancey & Watts greatly profited from direct connections to the British Army. The mercantile firm was headed by Oliver De Lancey, who had business offices at 54 Pearl.',
    '5. GW indulged in the luxury NYC had to offer, as his personal account books note pounds spent on horses, “Taylors Bill” or Tailor’s Bills, servants, and “Treating the ladies.”  One New York socialite, Mary Philipse (of the Morris-Jumel Mansion fame), supposedly caught the attention of the young Colonel during his visit. Introduced through Washington’s host, Beverly Robinson, there is no definite answer on the extent of their relationship. It is speculated Washington was a suitor to Mary Philipse and may have proposed, but no known correspondences exist between the two.',
    '5.1 Philipse later married Colonel Roger Morris in 1758, Morris was an acquaintance of Washington’s from the Braddock campaign. The Morris’ remained Tories following the break out of Revolution and the Morris-Jumel Mansion later served as Gen. Washington’s headquarters during the latter half of the New York campaign.',
    'Transition: The New York-based newspaper Mercury reported: “Friday last Colonel Washington set out from this city to Boston [February 23, 1756].” Washington’s trip to Boston ended in failure as the Massachusetts Governor did not grant GW the authority he sought within the royal army. Yet, Washington’s return to New York in the ensuing decades would grant him military recognition he seeked- but as General against the British Royal Army.'
  ]},
  {title: 'STOP #3 Washington’s Headquarters Flag (Flag Gallery): Revolutionary Beginnings (1773 - 1775)',
   slides: [
    '*Please Note: The flag seen above us is known as Washington’s Headquarters Flag or the Commander-in-Chief’s Standard. The flag marked the Gen. Washington’s presence throughout the Revolution and is said to be the earliest surviving 13-star flag.',
    '1. The Treaty of Paris (1763) ended the Seven Years’/French and Indian War. A victory for the British Empire, the French gave up their claim to all mainland North American territories- ending all foreign military threat to the colonies. Upon his return to civilian life, Washington was elected to the Virginia’s House of Burgesses and began a courtship with the colony’s wealthiest widow, Martha Dandridge Custis.',
    '2. (HANDOUT: Washington and his family) Married in 1759, Washington’s union to Martha resulted in no biological children. GW stepped into the role of surrogate father to Martha’s two young children from her previous marriage: John “Jack” Parke Custis and Martha “Patsy” Parke Custis. Washington never receiving a formal education himself, sought fit that John gain one as heir to Mount Vernon. In 1773, the decision was made to continue John Custis’ education at King’s College (now Columbia University) in New York.',
    '3. Prior to Washington’s visit in 1773, discontent among New Yorkers and the colonies as a whole began to grow- as colonists felt their rights as British citizens were under attack. Debt-ridden from the Seven Years’ War, Parliament began directly passing a series of taxes on the colonies, contrary to the ideal that only direct representatives from local government could pass taxes on the colonists. Taxes such as: The Stamp Act of 1765 on papered goods and The Townshend Act of 1767 on British imported goods (paint, glass, TEA, etc…) Aware of colonists’ protests, Parliament repealed the taxes- but the damage had been done.',
    '3.1 New York City was a center of protest in the years leading up to the Revolution. Mainly lead by the Sons of Liberty, encounters include: the creation and burning of an effigy of Royal Governor Cadwallader Colden at Bowling Green following the Stamp Act (1765), The Battle of Golden Hill- which may be seen as the first clash between colonists and redcoats (Jan 19, 1770), and the New York Tea Party (1774).',
    '4. Washington and his step-son John Custis arrived in New York on May 26, 1773. Washington promptly paid for his step-son’s college expenses and met with King’s College President Myles Cooper (a vocal Loyalist who later fled to England in 1775), requesting he watch over John Custis. During his visit, Washington attended a social gathering given in honor of General Thomas Gage- then Commander of the British troops in North America. GW served with Gage during the Braddock campaign in 1755, and before the close of his trip the two gentlemen once again met up for a small dinner. In two short years, the men would meet again- but as heads of opposing armies.',
    '4.1 John Custis didn’t stay at King’s College for very long. He returned to Mount Vernon the following month in June of 1773, as his sister Martha Custis later died that summer. He married in 1774 and remained in Virginia.',
    '5. The year 1775 was pivotal not only George Washington, but for the colonies as a whole. On June 15, 1775 Washington was unanimously chosen as Commander-in-Chief of the newly formed Continental Army. John Adams, who nominated GW, writes: “I can now inform you that the Congress have made Choice of the modest and virtuous, the amiable, generous and brave George Washington Esqr., to be the General of the American Army… This Appointment will have a great Effect, in cementing and securing the Union of these Colonies”. Beating out opponents for the position such as John Hancock, Washington’s appointment was due to his service during the Seven Years’ War and the belief that a leader from Virginia could unite the colonies towards one common cause.',
    '6. Upon his appointment, Washington swiftly left for Massachusetts to assume command of the Continental Army. On his trip north, the General passed through New York where he dined with members of the NY Provincial Congress and quickly left at nightfall en route to Boston.',
    'Transition: As Washington arrived in Massachusetts, the Continental Army was recovering from a recent defeat at the Battle of Bunker Hill (June 1775). The subsequent months left both the colonial and British armies at a stalemate. GW’s former acquaintance and British Commander Thomas Gage was recalled to London and the British Army, under the command of Gen. William Howe, evacuated Boston. As the British recuperated in Nova Scotia, General Washington knew the strategic location and advantage New York could provide to the enemy would make the city the next point of attack...'
  ]},
  {title: 'STOP #4 The Pulling Down of the King George III Statue (Fear and Force): Independence (1776)',
   slides: [
    '1. Washington arrived to New York City in mid-April of 1776 to oversee military  preparations [the General’s first recorded visit to Fraunces Tavern was on April 13, 1776]. Most able-bodied men, servants, and enslaved people were pressed into constructing fortifications all throughout the city. Additional structures were built along Upper Manhattan, Brooklyn, Governors Island, and NJ to prevent enemy entry. Yet, Manhattan surrounded by Hudson and East Rivers and New York Harbor led Washington to the conclusion that not all of New York could be protected. The unprotected shorefront presented the larger problem, as the Continental Congress had not assembled a Navy. In agreement with Congress, in order to boost American morale (as public opinion remained neutral), Washington fortified New York to the best of his ability.',
    '2. As preparations were underway those with no allegiance to either side and Tory sympathizers still inhibited the city. The Knickerbocker families of New York such as the Stuyvesants and the De Lanceys found their Townhouses over run by American soldiers, using their properties for supplies and stationing horses in their gardens. [Such as the case of Oliver De Lancey, who ordered patriot woodcutters off his property, in return the army burned his beloved orchards- the De Lancey family had sided with the English during the war.] Additionally, Washington ordered: “women, children, and infirmed persons in the City of New York to be immediately removed from the city.” This included residents of almshouse within the city.',
    '3. A Committee for the Detection of Conspiracies was created by the NY Provincial Congress, in order to combat the Tory problem within NYC. Under the leadership of John Jay, the committee discovered a plot against Washington, in which one of his bodyguards, Thomas Hickey, had conspired with others to kidnap or assassinate the general. Hickey was promptly court-martialed and hanged in front of a crowd of soldiers and civilians.',
    '3.1 You can make a brief mention of the legend surrounding Samuel Fraunces’ “daughter” Phoebe Fraunces. Legend states, Phoebe was the person to unfoil the plot against Washington, by learning Hickey’s plan to poison Washington’s peas. Yet, there are no records of a Phoebe Fraunces ever existing.',
    '4. (HANDOUT: British fleet anchored off Staten Island) On June 25th, 1776 (a day after Hickey’s execution) patriot lookouts witnessed the long-awaited British fleet sailing into New York Harbor. Within a 24-hour period, nine-thousand or so redcoats began to set about fortifying Staten Island. As tensions ran high among both sides, Washington urged his men to be ready at a moments notice. Shortly after the British appeared on NY shores, the Continental Congress in Philadelphia voted in favor of independence on July 2nd and adopted the Declaration of Independence, two days later on July 4th. The NY Provincial Congress approved of the document on July 9th and later that same day, under Washington’s general orders: “The several brigades are to be drawn up this evening on their respective Parades, at six OClock, when the declaration of Congress, shewing the grounds & reasons of this measure, is to be read with an audible voice.” The Declaration was read to Washington’s troops at the city commons (modern-day City Hall park), soldiers and civilians rallied behind Independence- to the point in which a mob developed.',
    '5. Following the public reading, a mob of soldiers and civilians marched down Broadway and on to Bowling Green. Erected on the green was an equestrian statue of George III, a symbolic regicide, the rowdy crowd toppled the statue and paraded the King’s lead head on a spike later placed near Fort Washington in Upper Manhattan (by present-day Broadway and 181st Street). In addition, the gate that encloses Bowling Green Park today is the very one that laid witness to the event. The rest of the statue, about four-thousand pounds of lead, was sent to Connecticut and melted into musket balls to use against the King’s Troops.',
    'Transition:  Three days later on July 12th, 1776, General Washington watched as two British warships detached themselves from the main English fleet off the shore of Staten Island. New Yorkers and American soldiers alike, witnessed the ships sail into New York Harbor and the Hudson River. The warships opened their gun ports and began blasting the Western shoreline of Manhattan. In a practice maneuver meant to test American fortifications, Washington’s plan for the city’s defense utterly failed, foreshadowing what was to come...'
  ]},
  {title: 'STOP #5: Brown Bess (Fear and Force): The Battle for New York (Summer of 1776)',
   slides: [
    '*The Brown Bess was the most common used musket during British Expansion, and would have been the combat weapon of choice for both the Redcoats and Americans. *',
    '6. Commander of British Troops, Gen. William Howe, did not wish for an all-out assault on New York City. Aware of the rising cost of war and men on both sides, Gen. Howe believed the possibility of reconciliation with the Americans could occur. Moreover, engaging in a grievous battle with Washington would annihilate any chance of reunion with the former colonies. And so, under the authorization of King George III, Gen. Howe’s brother Admiral Lord Richard Howe (Commander of the British Navy) was sent to the colonies as head of a commission to negotiate with the Contential Congress.',
    '7. The British warship Eagle sailed into New York in early July of 1776 carrying Admiral Howe and his peace commission. Following the British warship maneuver of July 12th, Washington wrote in a letter to John Hancock on July 14th: “About 3 OClock this afternoon I was informed that a Flag from Lord Howe was coming up and waited with two of our Whale boats untill direction should be given.” A barge carrying a white flag, an English soldier, and a letter addressed to “Mister Washington” was sent by Admiral Howe to greet the rebel army. The barge was met by Washington’s trusted aide Colonel Henry Knox, but he refused to accept such letter being there was “no person in our army with that address.” In addressing the letter “Mister Washington,” the British refused to recognize not only Washington and his army as combatants (rather than a mere gaggle of rebels), but in addition deny American independence and sovereignty.',
    '7.1 On July 15th, the Captain of Admiral Howe’s Ship, Eagle, returned to American lines with a newly addressed letter to “George Washington, Esq., and etc. etc.” Once again the letter was declined. Thus, putting an end to Admiral Howe’s peace commission.',
    '1. [HANDOUT: Map of the Battle of LI] British Generals Henry Clinton and Lord Charles Cornwallis arrived through the Narrows on August 1st, 1776, setting in motion a series of events that would lead to the Battle of Long Island, better known as the Battle of Brooklyn. Washington firmly believed the British would directly attack Manhattan Island, but as a precaution he placed General Israel Putnam in Brooklyn Heights and Gen. John Sullivan and Lord Stirling (Alexander McDougall) in the Heights of Guan to the South (Gowanus, Brooklyn). In a move that dramatically impacted the outcome of the battle, Washington failed to secure Jamaica Pass, a chain of hills, roughly located in current-day East New York, Brooklyn.',
    '1.1 Washington was greatly outnumbered, as Gen. Howe had about thirty-two thousand disciplined and equipped troops and thirteen thousand seamen under his command. In comparison, Washington had no ships nor seamen, and an estimated twenty-three thousand men (whom had very little training or proper equipment).',
    '2. On August 22, the British commenced their battleplan. Fifteen thousand redcoats landed at Gravesend Bay; stationed Patriot riflemen in the area offered little opposition and quickly withdrew. The lack of American reforment allowed for additional redcoats and Hessians (hired German auxiliaires) to enter Brooklyn: twenty-one thousand British troops in total. Washington believed this move was in-part a distraction, as he held onto the notion that the British would attack Manhattan. Reevaluating the situation, Washington dispatched reinforcements to Lord Stirling and placed Sullivan with about twenty-eight to about thirty-five hundred men to cover the Heights of Guan. *** Use Battle Map to help explain if need be.',
    '3. The British were notified of the neglected Jamaica Pass, and Gen. Howe, along with Clinton & Cornwallis, led ten-thousand men through the Flatlands and onto the Pass. On August 27th, the British were able to march through the Pass without opposition and launched their assault on American troops. The deadliest combat occurred to the South at the Heights of Guan between General Sullivan and the Hessian Commander Gen. Heister. Americans dropped their weapons and raced to reach the lines behind Brooklyn Heights, Sullvian himself ended up being captured at a location known as “Battle Pass” (A marker stands in place at Prospect Park today).',
    '4. [Handout: American retreat across Gowanus Creek] On August 28th, Washington was recorded to have been on Long Island to oversee fighting. Troops under Lord Stirling didn’t fare any better, as the Americans fought to keep the high ground at Battle Hill (located in Green-Wood Cemetery). As Redcoats closed in on Stirling\'s men, the American Commander counterattacked with four hundred men: the “Maryland 400.” Washington watching the encounter unfold between the British and Maryland troops, reportedly said: “Good God! What brave fellows I must this day lose!” The majority of brutal hand-to-hand combat happened along Gowanus Road, near the Cortelyou House (Old Stone House). As fighting waned, all but nine Marylanders were caught or killed, and Lord Stirling ultimately captured. The four hundred Maryland men, along with Lord Stirling, allowed for American forces to retreat behind Brooklyn Heights lines. After three days of heavy losses, [an estimated: 300 killed, 800 wounded, and 1,079 Missing/POW] Washington and his Council of War decided upon retreat from Long Island.',
    '5. The bulk of the Continental Army (roughly four to five thousand in total) and General Washington were encamped at Brooklyn Heights. Gen. Howe halted his troops (had he continued, the war would have ultimately ended at this point), allowing for Washington and his men to evacuate the island. On August 29th, miraculously concealed under a thick heavy fog, Washington transported his men (under strict orders to remain silent at all costs) across the East River to Manhattan. The last of the troops, and supposedly Washington himself, reached Manhattan at day-break. The following morning, the British discovered their mistake and Washington in a hasty move saved the Revolution.',
    'Transition: Four days later the British landed at Kips Bay (East 34th St), which resulted in a push by General Putnam to march American Troops upwards to Harlem Height. On September 16th, Washington headquartered at the Morris-Jumel Mansion, engaged in the Battle of Harlem Heights; his last push to defend New York (An American victory, and Washington’s first battlefield victory of the war). Additionally, Congress made the decision that New York should not be burned to the ground, yet on the night of September 21st lower Manhattan was engulfed in flames from Broad Street to the Western Shoreline (the causes of which are unknown). In which Washington wrote: “Providence, or some good honest fellow has done more for us than we were willing to do for ourselves.” Following defeats at both White Plans and Fort Washington, General Washington finally left New York City proper for good, not to return until 1783.'
  ]},
  {title: 'STOP #6: [Half-Stop] Sons of the Revolution: Collection Case: The Hudson Highlands  (1776 - 1779?)', slides: [
    '***The case to the left of Washington’s tooth and lock of hair; the objects on display are typical of items found at Continental fortifications. Be sure to point out Washington’s tooth and hair afterwards, this section does not cover the whole of Washington’s actions within the Hudson Highlands.***',
    '1. Following his defeat in New York, Washington would always be within a few days march from the city. Washington sought to maintain control of the Hudson River Highlands, controlling navigation between on both the Hudson River and the major Post Roads, between New York and Albany, and eventually onto the rest of the New England states.  As New York City remained under British control until the close of the war in 1783, the American General wanted to contain English influence.',
    '2. As early as Nov. 1775 a committee in Congress first recommended occupying an area 60 miles north of New York, the location would later become known as West Point. Situated on a plateau on the western bank of the Husdon, Washington believed West Point to be: “the most important Post in America.” By July 1776, West Point was one of the four fortifications in place to prevent British navigation. In 1778, the Great Chain (see below: a massive iron link chain placed underwater in the Hudson) was linked between West Point and Constitution Island to further halt any British activity.',
    '3. Following the 1777 American victory at Saratoga, the threat of British attack was still eminent. In 1779, Washington made a series of tactical decisions to ensure the Hudson Highlands remained under American control. Following British Commander Gen. Howe’s recall to London in 1778, General Sir Henry Clinton (no relation to Geogre Clinton) was set to replace him. Gen. Clinton devised a campaign in 1779 to gain control of the Hudson River and separate New England from the rest of the states.',
    '4. In May 1779, Clinton launched his campaign, his first notion was to raid Patriot ships within the Chesapeake Bay. As focus returned back to New York, Clinton wished to threaten the American stronghold at West Point. Washington in a letter to Gen. Philip Schuyler wrote in reference to West Point: “interrupt our easiest communication between the Eastern and Southern states, open a new source of supplies to them and a new door to distress and disaffect the country.” The British seized Kings Ferry (Lower Hudson River Valley) and the location’s two landing points Stony Point (The West bank of the Husdon) and Verplanck’s Point (East). Washington, headquartered at the Moore House in West Point, was able to establish troops on both sides of the Hudson (around Clinton’s men) to continue the supply line to New England. Washington stayed true to keeping forces around the Hudson during the summer of 1779, the British recoiled and by the end of the summer and lost 1,000 men.',
    'Transition: For Washington, the loss of New York City in 1776 was the greatest failure of his military career. Winning the city back would be a major point of consideration for Washington throughout the rest of the war. As the southern theater of the war became a more eminent issue, Washington still remained in the area with the main body of the Continental Army. Washington patiently waited for the right moment to strike, even constructing what he called his “Grand Strategy” in 1778. Both French and British forces were committed to the southern theater, and Washington’s strategy was never put into place. Until the arrival of Count Rochambeau (commander of the French army) in 1780, did Washington leave the area to implement the “Grand Strategy” in the Chesapeake Bay in what became known as the Siege of Yorktown. Yet, throughout Washington’s station in the tri-state area he took another course of action in regards to New York City.'
  ]},
  {title: 'STOP #7: The Tallmadge Memoirs: British NYC and the Spymaster (1778-1783)',
   slides: [
    '***The Tallmadge Memoirs are known for its telling of Washington’s Farewell Speech. Yet, the man behind the writing played an important role during the war- for he was the center of Washington’s Culper Spy Ring based out of New York City.***',
    '1. On September 11th, 1776 in a last attempt by the both the American Congress and Lord Richard Howe, a meeting occurred to mend the broken relationship between Mother England and her colonies. Now known as the Conference House on Staten Island, American representatives John Adams, Benjamin Franklin, and Edward Rutledge met to negotiate agreeable terms in which the British would recognize American independence. Both sides failed to reach an agreement and another seven year of war (along with the definite loss of NYC for the duration of the war) was inevitable.',
    '2. The city GW left in flames was changing rapidly under British occupation. At the start of its occupation towards the end of August 1776, the port city became the nerve center of loyalist activity throughout the war. Loyalists from surrounding areas sought refuge in New York City, including enslaved people in the hopes of obtaining freedom under British promises of freedom through Lord Dunmore’s proclamation of 1775 (Dunmore actually made it to NY shores in 1777). The British imposed martial law within city limits to maintain control, although English soldiers were known to frequent the city’s growing red light district and loot patriot owned properties. The flood tide of loyalist refugees continuously grew, by early 1777 the city’s population was at 12,000 - in 1779 it reached upwards of 33,000. As New York City became the “Gibraltar of North America,” as a British commander put it (an allusion to the reinforced royal fort at Gibraltar), Washington understood the wealth of enemy information flowing through Manhattan’s streets.',
    '2.1 Wallabout Bay or the current-day Brooklyn Navy Yard, served as a holding place for many Patriot POWs. Imprisoned on British naval ships, most infamous being the HMS Jersey, the conditions were cramped and unsanitary. An estimated 11,000 passed on the floating prisons (the most American losses throughout the war occurred here, more than Americans suffered on the battlefield). The Prison Ship Martyrs Monument in Fort Greene stands as a testament to this grim chapter in American History (For reference, Wallabout Bay is depicted on the Razter Map).',
    '3. [HANDOUT Map of Culper Spy Ring Route] In 1778, Long Island native, Major Benjamin Tallmadge (a Yale Graduate and Battle of Brooklyn veteran) was appointed by General Washington as the Director of Military Intelligence with the orders of securing information on the British in New York City. In what became known as the Culper Spy Ring, (the name derives from Culpeper Co., VA- which Washington surveyed during his early career) Tallmadge and a network of close aquinances (Abraham Woodhull, Caleb Brewster, Anna Smith-Strong, and Robert Townsend) created a of flow of American intelligence from New York Harbor, to Long Island’s North Shore, and finally onto CT- where Tallmadge himself would deliver information to Washington.',
    '4. Washington implemented a series of tactics to gather intelligence, as well as confuse the New York Loyalist community:',
    '4.1 Washington in order to further throw off opponents, encouraged members of the Spy Ring to spread disinformation. He asked members to exaggerate the size and strength of his troops, as well as false military plans in regards to troop movements and attacks.',
    '4.2 A system of three digit numbers served as words or phases was devised to encrypt the ring’s information, in case the intel would fall into the wrong hands (ex: Washington:711, New York: 727, Long Island: 728, Tallmadge: 721, more codes provided in the link below).',
    '4.3 The Spy Ring began recruiting and sending female spies into the city, under the impression of delivering food and supplies to relatives. They gathered valuable intel on British patrol movements, in passing the information they would hang “black petticoats and an agreed number of white handkerchiefs” on a clothesline  at Boarding house on Queen Street.',
    '4.4 Additionally, they utilized a variety of code names assigned to lead contributors in order to maintain secrecy. Important to the spy ring was Robert Townsend or “Samuel Culper, Jr.” a loyalist coffee-shop owner and society reporter who would pass intel overheard at British gatherings over to Abraham Woodhull or “Samuel Culper” to transport across Long Island to secret locations known as “dead drops” (Tallmadge’s alas was “John Bolton”).',
    '4.5 The role these two men played in the Culper Spy Ring is not to be understated, Tallmadge and Washington would often refer to the Culpers in their correspondence. An example of a typical letter from Washington to Tallmadge is seen blow from Dec. 17, 1778.',
    'Dear Sir: I have your favor of the 11th in closing a letter from C——. when I desired an interview with him I did not know his peculiar situation. I now see the danger that so long an absence would incur and I must leave it entirely to you to manage the correspondence in such a manner as will most probably ensure safety to him and answer the desired end. I am &ca.',
    'Transition: Only a fraction of the intelligence work done during the war; the actions of the Culper Spy Ring helped to ultimately defeat the British in 1781. In 1780, the ring uncovered a planned English attack on French troops en route to aid the Americans. With advance warning, Washington prepared a defense and the British withdrew from their plans. Moreover, the ring worked to capture Major John Andre, who was known for his collusion with the infamous turncoat Benedict Arnold. Washington and Tallmadge’s work within the New York Spy Ring laid the groundwork for today’s intelligence community and without said work the outcome of the American Revolution might have been drastically different. The Culper Spy Ring’s activity ended in 1783, as the British withdrew from NYC and Washington in his victorious return, stepped onto the shores of Manhattan for the first time seven years…'
  ]},
  {title: 'STOP #8: The Long Room: End of War and Farewell Speech (1781-1783)',
   slides: [
    '***The Long Room is the sight of Washington’s Farewell Speech, in which he withdrew from his post as Commander-in-Chief and bid farewell to his officers***',
    '1. Aided by French Land and Naval forces, the Contenital Army under the command of Gen. Washington laid siege to English troops, in what became known as the Battle of Yorktown. On October 19th, 1781 a white flag emerged from the English encampment and Lord Cornwallis offer his terms of surrender to Gen. Washington. Cornwallis’ defeat at Yorktown, set in motion a series of negotiations that led to the signing of the Treaty of Paris in 1783 (completely different document from the earlier ‘63 treaty).',
    '2. During the intermittent years of 1781 to 1783, New York City still remained under British control. Upon a public reading of the Royal Proclamation of February 1783, officially suspending hostilities, New York crowds responded with “groans and hisses.” English soldiers deserted posts and worried civilians sold their properties, gathered belongings, and fled the city- either to England or the English held territories in Canada. The enslaved and freed refugees faced recapture by American slaveholders, Washington in conversation with Sir Guy Carleton (head of British NYC at the time) stated, “he wanted the British to return all runways to their rightful owners.” Black refugees who escaped the city settled in Nova Scotia or New Brunswick, or even made it to England, but many were taken from the streets of New York and placed back into the chains of bondage. The British and those loyal to the English Crown officially left the city on November 25th 1783, known as Evacuation Day Major General Henry Knox marched into the city and took possession. A contingent of Continental officers (including Alexander McDougall or Lord Sterling) and eight hundred soldiers met Washington and New York State Governor George Clinton at the Bowery and together they made their formal entrance back into New York City.',
    '3. [HANDOUT Washington and his troops traveling up Broadway] The procession marched down from the Bowery onto Pearl Street, turned along Wall Street and made their way to Broadway. As British Troops departed the city, in a parting insult- left the royal ensign on a greased pole in front of Front George (now the National Archives/National Museum of the Native American or 1 Bowling Green). Wearing cleats and with Washington watching from a distance, a man by the name of John Van Arsdale climbed up the pole and replaced the ensign with the Stars and Stripes. This became a celebrated New York City tradition on Nov. 25th, but a shift in the holiday\'s popularity occurred around America\'s entrance into World War I, thus much fanfare ended- interestingly due to an alliance with Great Britain. Later the same evening, Governor Clinton hosted a public banquet in honor of Washington and his men at Fraunces Tavern in Clinton Dining Room across the hall, aptly named due to the event.',
    '4. On December 4th, 1783, following the celebration of New York City’s return into American hands, Washington once again invited his officers to the Long Room of Fraunces Tavern. According to the Tallmadge memoirs, Washington laments: “With a heart full of love and gratitude, I now take leave of you. I most devoutly wish that your latter days may be as prosperous and happy as your former ones have been glorious and honorable.” Washington in an unprecedented move, bid farewell to this officers before he stepped down from his post as General of the Continental Army, in hopes of once again pursuing the life of Vrginian farmer. After seven years of service with these men, the event was marked with “extreme sensibility on both sides” as Washington took  each one of them in hand. Following the farewell, Washington, escorted by a column of infantrymen, walked down Whitehall Street where a barge waited to take him across to NJ and onto Annapolis, Maryland to hand in his resignation to Congress on Dec. 23, 1783.',
    '4.1 Possible people at the speech: Henry Knox, George Clinton, Benjamin Tallmadge, Lord Stirling, Thaddeus Kosciuzko…',
    'Transition: Following his resignation to Congress, on Dec. 23 Washington returned to his beloved estate of Mount Vernon. He sought to devote himself to projects in and around his property. Yet, as the new nation was looking to pave the way for a constitutional government- Washington was once again called into public life and back onto New York’s street.'
  ]},
  {title: 'STOP #9: Scott Gallery- Hallway Looking Out to Broad Street: Presidency and Conclusion (1789-1792)', slides: [
    '***Here we are faced with Washington’s legacy, and the precedent he set as the first President of the United States***',
    '1. “The scene is at last closed. I feel myself eased of a load of public care. I hope to spend the remainder of my days, in cultivating the affections of good men, and in the practice of the domestic virtues.”- George Washington, 1783.  A civilian of the newly independent United States of America, Washington looked forward to private life within the realms of his Mount Vernon estate. He took to agricultural experiments and correspondence, as well as play an active role in family life as grandfather to Nelly and George Washington Custis.'
  ]},
  {title: '10. EXTRA',
   slides: [
    '1. *[Yet, the nation was entering a turbulent period, the government- a loose Confederation of States, weakly bound together by the Articles of Confederation (1777), mainly gave power to the States. The new nation, riddled with debt and a weak Congress, made little pay to the soldiers who were promised reimbursement for their service. Angered by the increase in tax by the state of Massachusetts, a former veteran Daniel Shay led an insurrection across the Massachusetts countryside from 1786 to 1787. In a letter 1786 to James Madison, Washington writes: “Thirteen Sovereignties pulling against each other, and all tugging at the foederal [Federal] head will soon bring ruin on the whole; whereas a liberal, and energetic Constitution, well guarded and closely watched, to prevent incroachments [encroachments], might restore us to that degree of respectability and consequence.” Shays’ Rebellion would be the push to a constitutional government, the one in which we draw upon today. Alexander Hamilton (Camp-de-aide to Washington during the war and representative from NY) following the Annapolis Convention of 1786 called for another convention to meet in Philadelphia the following year: “[to] render the constitution of the federal government adequate to the exigencies of the Union.” From May 14th to Sept. 17th 1787, delegates from across the United States held a closed-door meeting in Philadelphia in debate for a stronger Federal Government. A call for change, Washington was persuaded to attend by James Madison and Gen. Henry Knox, he was unanimously elected as president of the convention. GW did not take a direct stance on debate, but rather served as a moderator for the delegates. What resulted from this four month assembly and politicking on behalf of the delegates to their respective states, was the ratification of the US Constitution.]*',
    '2. Yet, the nation was entering a turbulent period, the government- a loose Confederation of States, weakly bound together by the Articles of Confederation (1777), mainly gave power to the States. Thus, the Constitution was ratified in 1787 creating a strong Federal government devised of three central branches: Legislative (Senate and the House of Representatives), Executive (President), and Judicial (Supreme and lower Courts). During the first presidential election of 1789, GW was unanimously elected president of the United States with 69 electoral votes- winning the support of each participating elector (John Adams came in second, and thus according to the constitution at the time was to serve as Vice President- a role in which he was not happy with). Once again pulled away from civilian life, George Washington traveled up north, to the nation’s new capital New York City (land-rich, but cash-poor he actually had to take a loan out on his carriage ride up North). An eight day trip, his travels included grand marches through six states and cities such as Alexandria, Baltimore, Wilminton, and Philadelphia- almost shadowing his first trip up to New York in 1756. Thousands of citizens lined the road to New York, and on April 23, 1789 on a barge symbolical manned by thirteen harbor-pilots in white uniforms- he came ashore by Murray’s Wharf at the foot of Wall Street.',
    '3. [HANDOUT: Print of Inauguration] On April 30, 1789, the city awakened at dawn to salute from guns on the Battery- it was Washington’s inauguration day. Congress assembled at noon, but with no precedents to draw on there was some confusion over formalities- no one brought a Bible. Jacob Morton, a Mason at the nearby St. John’s Lodge offered to retrieve a Bible from the Lodge. Washington stepped onto the second-floor balcony of Federal Hall dressed in plain brown American broadcloth [GW understanding the value of this day, purposely chose this dress made from a mill in Hartford, CT. He said: “[would] be unfashionable for a gentleman to appear in any other dress”- than one of American manufacture]. Administered by Robert R. Livingston, Washington performed the Oath of Office on the Masonic Bible. The crowds down Broad Street cheered: “Long Live George Washington, President of the United States!”',
    '3.1 Federal Hall located at the intersection of Broad and Wall street no longer stands. The 1840s Sub-Treasury stands there now as Federal Hall National Memorial. The inauguration Bible is currently on show, list of past presidents sworn-in on the Bible are: Harding, Eisenhower, Carter, and George H.W. Bush.',
    '1. Following the event, GW delivered his inaugural address to a joint-session of Congress inside the Senate chambers. Following the address, Washington and members of Congress walked to St. Paul’s on Broadway for service. For the rest of the day, most of New York celebrated as fireworks decorated the skies- “Washington, who watched the show from Chancellor Livingston’s house, had to get home on foot because the streets were too full of people for his carriage to pass.”',
    '2. New York served as the nation’s capital from 1785 to 1790, and so Washington’s stay as president here was brief. Martha Washington arrived in May 1789, and the family took residence on 3 Cherry Street. The household staff included fourteen servants and the household steward, who was none other than Samuel FrauncesThe Washingtons also brought along seven enslaved people, including Washington’s personal body servant William Lee. Important to note, the Washingtons would often rotate their enslaved staff every six months, because due to northern laws they would have to be freed. Washington’s first few months in office were shadowed by poor health, in fact- in June 1789 “fifteen pounds of rope was purchased to extend across the street to prevent the passing of carriages during the President’s illness.”',
    '2.1 In wanting Fraunces on the staff Washington wrote: “Fraunces, besides being an excellent cook, knowing how to provide genteel dinners, and giving aid in dressing them, prepared the dessert and made the cake.”',
    'End: By July 1789, Washington was well enough to return to office, but while in New York he knew his goal was to develop the American presidency- every move he made set a precedent in both political and social aspects of the office. One of his most important contributions was the development of a Presidential Cabinet: Secretary of State Thomas Jefferson, Secretary of the Treasury Alexander Hamilton, and Attorney General Edmund Randolph. The capital moved from NYC to Philadelphia in the Summer of 1790 and with it, Washington and his family. The rest of his Presidency was fought over international and domestic affairs such as trade with the British, the issue of the French Revolution, dealings with European empires in Western Territories, and building the foundation of the United States government as a whole...',
    'His dealings with New York impacted his public career in some shape or form- from young soldier, seasoned General, and finally President of the United States. Most importantly as seen by the room we are standing in, Washington’s restraint and solemnity throughout his public career: crossing the East River in the midst of defeat, the creation of an intelligence ring throughout New York, the farewell speech, stepping out of civilian life to lead the nation- created an image of greatness. “He was the man who could have been a king but refused a crown and saved a republic.”'
  ]}
]

export { tour };
